### ISSUE TITLE
Improve exception reporting

### ISSUE THREAD

**Issue by hanshuebner** [daveliepmann/uruk#5] opened 2016-07-17 08:53 UTC
Currently, XQuery parse and other MarkLogic errors are reported only superficially:

```
  Show: Clojure Java REPL Tooling Duplicates All  (11 frames hidden)

1. Unhandled com.marklogic.xcc.exceptions.XQueryException
   Unexpected token

ServerExceptionHandler.java:   34  com.marklogic.xcc.impl.handlers.ServerExceptionHandler/handleResponse
EvalRequestController.java:   96  com.marklogic.xcc.impl.handlers.EvalRequestController/serverDialog
AbstractRequestController.java:   88  com.marklogic.xcc.impl.handlers.AbstractRequestController/runRequest
          SessionImpl.java:  437  com.marklogic.xcc.impl.SessionImpl/submitRequestInternal
```

I think the exceptions contain very detailed information as to where the error is, and that should be made available to uruk users directly.

**Comment by daveliepmann** [comment] 2016-07-18 19:54
This issue seems to be caused by MarkLogic overriding [Throwable.toString](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#toString--) in [XQueryException](https://github.com/marklogic/xcc-java/blob/master/com/marklogic/xcc/exceptions/XQueryException.java#L156), which becomes a problem somewhere down the line when the exception is inspected with .getClass and .getLocalizedMessage rather than .toString.

Both cider and `lein repl` fail to return the complete .toString information, which suggests to me that this stems from a bug in leiningen. I am investigating.

**Comment by daveliepmann** [comment] 2016-07-18 20:42
Correction: the error may be in nrepl

**Comment by daveliepmann** [comment] 2016-07-18 22:05
Try version 0.2.1 for the moment. Fix is in 58527823dca57bc10cf5dd6ac3959d1e867ae85b.

It's not an ideal solution, but this at least provides a simple way for users to get all the info from emacs/cider. I am looking for a good way to pass the whole exception along, stack trace intact, with the unclipped message too.

**Comment by daveliepmann** [comment] 2016-07-18 22:56
Version 0.2.2 slightly improves error handling by using slingshot. Currently the only lossy factor is that all errors come through as `Unhandled java.lang.Exception` rather than specifically, for example, `com.marklogic.xcc.exceptions.XQueryException`. This information is however preserved in the message immediately following.

I'm closing this for now, but let me know if a different approach is needed.

**Closed as completed by daveliepmann** 2016-07-18 22:56 UTC
Labels: bug

**Comment by hanshuebner** [comment] 2016-07-19 05:38
Works great, thanks!

**Comment by hanshuebner** [comment] 2016-07-19 05:40
I do wonder why the error message seems to be printed out of order somehow:

```
molina-provider-report.cli> (molina-provider-report.report/get-registry-history "1326206939")
Exception com.marklogic.xcc.exceptions.XQueryException: XDMP-UNEXPECTED: (err:XPST0003) Unexpected token syntax error, unexpected QName_, expecting $end or SemiColon_
 [Session: user=restuser, cb=mpr [ContentSource: user={none}, cb={none} [provider: address=marklogic/172.16.0.15:8884, pool=1/64]]]
 [Client: XCC/8.0-5, Server: XDBC/8.0-5]
on line 7
expr:    com.marklogic.xcc.impl.handlers.ServerExceptionHandler.handleResponse (ServerExceptionHandler.java:34)
```

**Comment by daveliepmann** [comment] 2016-07-19 14:48
It's the `XQueryException.toString` override, which arranges the output in [an idiosyncratic order](https://github.com/marklogic/xcc-java/blob/master/com/marklogic/xcc/exceptions/XQueryException.java#L156). Printing of database details is determined in [RequestException.appendRequestInfo](https://github.com/marklogic/xcc-java/blob/4a7ade0a546bbcbd8dd71a8e9829950b0169a842/com/marklogic/xcc/exceptions/RequestException.java#L57).

**Comment by hanshuebner** [comment] 2016-07-19 14:55
It would be more useful if the request info would be appended at the end of the message, rather than in the middle of it.  Also, it would be useful if there was information as to what "line 7" refers to - If a file was evaluated, what was the file?  If it was a literal string, what was that string?

**Comment by daveliepmann** [comment] 2016-07-19 15:23
Line 7 is in the XQuery query itself. ML usually doesn't say what the literal string is. 

I'm wary of getting into the business of parsing and rewriting error report strings, but I can look into it.

**Comment by hanshuebner** [comment] 2016-07-19 15:59
Sorry, I was wrongly assuming that the XCC code was part of uruk :)  We definitely do not want to mess around with error messages that they compose.  Let's keep it as it is for now.
